### PR TITLE
Remove blueprintjs & update webpack-dev-server

### PR DESCRIPTION
**Pull request by by-co**
## Clean up & update packages
- remove blueprintjs (no longer used)
- update webpack-dev-server (should fix vulnerability warning)
- install classnames (was a dependency in `blueprintjs`)

### Related PRs
#22

### CODE REVIEW

**Comment by by-co** [comment]
@emilyzhong Can you review to see if everything works w/ new webpacker?

**Comment by by-co** [comment]
@amyshan Can you check if everything is good and fine :')

**Comment by by-co** [comment]
@emilyzhong Hmm, I'm not seeing the `htmlFor` error 😮 `Filters` is the only component that uses `<label>` and I think I made that diff in this PR

**Comment by emilyzhong** [comment]
o lmao error doesn't show up anymore everything is good! sorry about that D:

**Pull request merged**
